spring:
  redis:
    host: localhost
    port: 6379
    jedis:
      pool:
        max-active: 20
        max-idle: 10
        min-idle: 5
    timeout: 5000
server:
  servlet:
    context-path: /springboot4redis
  port: 80